name: DevOps Training Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Get the code from repo
      uses: actions/checkout@v3

    - name: Setting up the golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Installing packages/library
      run: go mod tidy

    - name: Run the test cases
      run: go test -v ./...